In [30]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("./deeplearning.mplstyle")

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [32]:
# make  dataset for example
from sklearn.datasets import make_blobs
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(
    n_samples=2000, centers=centers, cluster_std=1.0, random_state=30)

In [33]:
print(f"X_train size: {X_train.shape}")
print(f"y_train size: {y_train.shape}")

X_train size: (2000, 2)
y_train size: (2000,)


## model 1

In [34]:
# Method 1

model = Sequential(
    [
        Dense(units=25, activation="relu"),
        Dense(units=15, activation="relu"),
        Dense(units=4, activation="softmax")
    ]
)

model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.001)
              )
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
63/63 [==============================] - 1s 1ms/step - loss: 1.0320
Epoch 2/10
63/63 [==============================] - 0s 1ms/step - loss: 0.4677
Epoch 3/10
63/63 [==============================] - 0s 1ms/step - loss: 0.2013
Epoch 4/10
63/63 [==============================] - 0s 1ms/step - loss: 0.1118
Epoch 5/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0797
Epoch 6/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0641
Epoch 7/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0548
Epoch 8/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0486
Epoch 9/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0445
Epoch 10/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0404


In [35]:
p_nonpreferred = model.predict(X_train)
print(p_nonpreferred[:2])
print("largest value", np.max(p_nonpreferred),
      "smallest value", np.min(p_nonpreferred))

63/63 [==============================] - 0s 1ms/step
[[6.789838e-03 5.699844e-03 9.672055e-01 2.030476e-02]
 [9.915924e-01 8.359187e-03 3.140930e-05 1.705505e-05]]
largest value 0.9999996 smallest value 1.0469903e-08


In [36]:
for i in range(5):
    print(
        f"{np.round(p_nonpreferred[i], 4)}, category: {np.argmax(p_nonpreferred[i])}")

[0.0068 0.0057 0.9672 0.0203], category: 2
[0.9916 0.0084 0.     0.    ], category: 0
[9.431e-01 5.620e-02 5.000e-04 2.000e-04], category: 0
[0.0046 0.9903 0.0038 0.0012], category: 1
[4.100e-03 2.000e-04 9.955e-01 2.000e-04], category: 2


## preferred model

In [37]:
preferred_model = Sequential(
    [
        Dense(units=25, activation='relu'),
        Dense(units=15, activation='relu'),
        Dense(units=4, activation='linear')
    ]
)

preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001)
)
preferred_model.fit(X_train, y_train, epochs=10)

Epoch 1/10
63/63 [==============================] - 1s 1ms/step - loss: 1.0807
Epoch 2/10
63/63 [==============================] - 0s 1ms/step - loss: 0.4579
Epoch 3/10
63/63 [==============================] - 0s 1ms/step - loss: 0.1792
Epoch 4/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0981
Epoch 5/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0717
Epoch 6/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0596
Epoch 7/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0520
Epoch 8/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0468
Epoch 9/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0427
Epoch 10/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0396


In [38]:
# z values
z_preferred = preferred_model.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:2]}")
print("largest value", np.max(p_preferred),
      "smallest value", np.min(p_preferred))

63/63 [==============================] - 0s 1ms/step
two example output vectors:
 [[3.0816258e-03 7.0663374e-03 9.7598356e-01 1.3868520e-02]
 [9.9661618e-01 3.2887831e-03 9.1488480e-05 3.4659649e-06]]
largest value 0.99999946 smallest value 4.3130224e-10


In [39]:
p_preferred = tf.nn.softmax(z_preferred).numpy()

In [40]:
print(f"two example output vectors:\n {p_preferred[:2]}")
print("largest value", np.max(p_preferred),
      "smallest value", np.min(p_preferred))

two example output vectors:
 [[5.1429919e-03 3.1480452e-03 9.7724622e-01 1.4462727e-02]
 [9.9698681e-01 2.8887929e-03 1.2084785e-04 3.4264472e-06]]
largest value 0.9999985 smallest value 1.1614388e-10


In [41]:
for i in range(5):
    print(f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

[0.00514299 0.00314805 0.9772462  0.01446273], category: 2
[9.9698681e-01 2.8887929e-03 1.2084785e-04 3.4264472e-06], category: 0
[9.7424650e-01 2.4548864e-02 1.1370374e-03 6.7607049e-05], category: 0
[0.00693363 0.98770386 0.00418718 0.00117528], category: 1
[6.9286977e-03 3.4740835e-05 9.9297202e-01 6.4550601e-05], category: 2
